### ISSUE TITLE
Schema is missing `CodedEvent_SNOMED` table

### ISSUE THREAD

**Issue by evansd** [opensafely/tpp-database-schema#49]
This is **not** a defect in this repo – it is something only TPP can fix for us – but this felt like the most appropriate place to record it for future reference.

---

The `CodedEvent_SNOMED` table is effectively a  parallel copy of the `CodedEvent` table but with SNOMED-CT codes instead of CTV3. Due to it's size I believe it goes through a slightly different build process to the rest of the tables. Possibly this accounts for the fact that it is not included in the schema description table.

For now, we can include it manually based on the schema details we already have in Cohort Extractor:
https://github.com/opensafely-core/cohort-extractor/blob/bdf82919/tests/tpp_backend_setup.py#L150-L161

But it would be better if we didn't have to do this.

**Comment by iaindillingham** [comment]
I'll ask Chris whether `CodedEvent_SNOMED` can be added to `OpenSAFELYSchemaInformation`.

**Comment by iaindillingham** [comment]
Added by #80 and incorporated in ehrQL by opensafely-core/ehrql#1511. The reason it wasn't included in the report wasn't its omission from `OpenSAFELYSchemaInformation` (and hence a TPP issue) it was because rows without a value for the `DataSource` column were filtered out (and hence our issue). Sorry about that!
